Tensors are Multi Dimentional arrays
An array is an ordered arrangement of numbers

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d = tf.constant(4) #tensor_zero_d is a 0-d tensor with value 4
print(tensor_zero_d)

tensor_one_d = tf.constant([2.3,0,-3]) #tensor_one_d is a 1-d tensor with value [2,0,-3]
print(tensor_one_d)

tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]]) #tensor_two_d is a 2-d tensor with value [[1,2,0],[3,5,-1],[1,5,6][2,3,8]]
print(tensor_two_d)

tensor_three_d = tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [1,5,6],
        [2,3,8]
    ],
    [
        [4,2,3],
        [5,1,2]
    ]
])
print(tensor_three_d) #tensor_three_d is a 3-d tensor with value [[[1,2,0],[3,5,-1]],[[1,5,6],[2,3,8]],[[4,2,3],[5,1,2]]]
print(tensor_three_d.shape) #shape of tensor_three_d is (3,2,3) which means 3 matrices of 2x3
print(tensor_three_d.ndim) #dimension of tensor_three_d is 3

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([ 2.3  0.  -3. ], shape=(3,), dtype=float32)
tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[ 1  5  6]
  [ 2  3  8]]

 [[ 4  2  3]
  [ 5  1  2]]], shape=(3, 2, 3), dtype=int32)
(3, 2, 3)
3


In [4]:
casted_tensor_one_d = tf.cast(tensor_one_d, tf.int32) #casting tensor_one_d to float32 
print(casted_tensor_one_d)  

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [5]:
tensor_bool = tf.constant([True, False, False, True]) #tensor_bool is a 1-d tensor with value [True, False, False, True]
print(tensor_bool)
tensor_string = tf.constant(["Hello, World!","Hi"]) #tensor_string is a 0-d tensor with value "Hello, World!"
print(tensor_string)

tf.Tensor([ True False False  True], shape=(4,), dtype=bool)
tf.Tensor([b'Hello, World!' b'Hi'], shape=(2,), dtype=string)


In [6]:
import numpy as np

In [7]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [8]:
converted_tensor = tf.convert_to_tensor(np_array)#converting numpy array to tensor
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


eye() functionality is used to generate identity matrix

In [9]:
eye_tensor = tf.eye( 
    num_rows=5,
    num_columns=5,
    batch_shape=[3], #shape of the batch of matrices
    dtype=tf.dtypes.int16,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]

 [[1 0 0 0 0]
  [0 1 0 0 0]
  [0 0 1 0 0]
  [0 0 0 1 0]
  [0 0 0 0 1]]], shape=(3, 5, 5), dtype=int16)


tf.fill():
Creates a tensor filled with a scalar value

tf.ones(shape,
dtype = tf.dtypes.float32,
name= None):
Creates a tensor with all elements set to one (1)

tf.ones_like(
    input,dtype = None,name = None
):
Creates a tensor of all ones that has the same shape as the input

tf.zeros()
Creates a tensor with all elements set to zero

In [10]:
fill_tensor = tf.fill(
    [3,4],5,#3*4 matrix with all elements as 5
    name="5-matrix"
)

print(fill_tensor)

ones_tensor = tf.ones(
    [2,3],#2*3 matrix with all elements as 1
    tf.dtypes.int32,
    name="1-matrix"
)

print(ones_tensor)

ones_like_tensor = tf.ones_like(
    fill_tensor,
    dtype=None,
    name="ones_like_tensor"
)

print(ones_like_tensor)

zeros_tensor = tf.zeros(
    [3,4],#3*4 matrix with all elements as 0
    tf.dtypes.int32,
    name="0-matrix"
)
print(zeros_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [11]:
t = tf.constant([[1,2,3],[4,5,6]])
tf.rank(t) 
tf.size(t, out_type=tf.dtypes.int32)


<tf.Tensor: shape=(), dtype=int32, numpy=6>

tf.random.normal(
    shape,
    mean = 0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed = None,
    name=None
):
Outputs random values from a normal distribution

In [12]:
random_tensor = tf.random.normal(
    [3,4],
    mean=10.0, # the numbers are near to 10 as we gave mean as 10
    stddev=1.4, #the variation from 10 is depedned on the standard deviation
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 9.496778 10.874689  9.029537  8.820302]
 [11.122498 12.495474 10.369982 10.884469]
 [ 9.212329 10.522087 10.826908 10.617887]], shape=(3, 4), dtype=float32)


In [13]:
random_tensor = tf.random.uniform(
    [5,],
    minval=95, 
    maxval=100, 
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor([98.6429   99.729126 95.10134  99.63769  96.84608 ], shape=(5,), dtype=float32)


In [14]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,4],maxval = 9,dtype=tf.dtypes.int32 , seed=1))


tf.Tensor(
[[3 7 5 4]
 [1 4 6 8]
 [4 1 8 4]], shape=(3, 4), dtype=int32)


Indexing

In [15]:
tensor_indexed = tf.constant([3,16,2,4,6,14,7])
print(tensor_indexed) 
print("Indexing the tensor")
for i in range(tensor_indexed.shape[0]):
    print(tensor_indexed[i])
print("slicing the tensor")
print(tensor_indexed[0:4]) #slicing the tensor from index 1 to 4


tf.Tensor([ 3 16  2  4  6 14  7], shape=(7,), dtype=int32)
Indexing the tensor
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(14, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
slicing the tensor
tf.Tensor([ 3 16  2  4], shape=(4,), dtype=int32)


In [16]:
tensor_indexed_2d = tf.constant([ 
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_indexed_2d)
print("Indexing the tensor")
for i in range(tensor_indexed_2d.shape[0]):
    for j in range(tensor_indexed_2d.shape[1]):
        print(tensor_indexed_2d[i][j])

print("slicing the tensor")
print(tensor_indexed_2d[0:2,0:2]) #slicing the tensor from index 1 to 4

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Indexing the tensor
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
slicing the tensor
tf.Tensor(
[[1 2]
 [4 5]], shape=(2, 2), dtype=int32)


In [17]:
tensor_indexed_3d = tf.constant([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(tensor_indexed_3d)
print("Indexing the tensor")
for i in range(tensor_indexed_3d.shape[0]):
    for j in range(tensor_indexed_3d.shape[1]):
        for k in range(tensor_indexed_3d.shape[2]):
            print(tensor_indexed_3d[i][j][k])

print("slicing the tensor")
print(tensor_indexed_3d[0:1,0:1,0:2]) #slicing the tensor from index 1 to 4

tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Indexing the tensor
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
slicing the tensor
tf.Tensor([[[1 2]]], shape=(1, 1, 2), dtype=int32)


tensor math

In [18]:
x_abs = tf.constant([1,-2,0,3])
print(tf.abs(x_abs))
complex_abs = tf.constant([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(tf.abs(complex_abs))

tf.Tensor([1 2 0 3], shape=(4,), dtype=int32)
tf.Tensor([5. 5. 2. 1.], shape=(4,), dtype=float64)


In [19]:
tf.sqrt(tf.cast([1.0, 4.0, 9.0], tf.float32))  # [1.0, 2.0, 3.0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [20]:
x1 = tf.constant([1, 2, 3], dtype=tf.float32)
x2 = tf.constant([4, 5, 6], dtype=tf.float32)
print(tf.add(x1, x2))  
print(tf.subtract(x1, x2))
print(tf.multiply(x1, x2))
print(tf.divide(x1, x2))
x3 = tf.constant([0.5, 0, 1], dtype=tf.float32)
print(tf.math.divide_no_nan(x1, x3))

tf.Tensor([5. 7. 9.], shape=(3,), dtype=float32)
tf.Tensor([-3. -3. -3.], shape=(3,), dtype=float32)
tf.Tensor([ 4. 10. 18.], shape=(3,), dtype=float32)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float32)
tf.Tensor([2. 0. 3.], shape=(3,), dtype=float32)


In [21]:
x_argmax = tf.constant([[61, 38, 26, 65, 44, 36],
                        [10, 15, 82, 42, 78, 43],
                        [71, 30, 22, 57, 42, 16]])
x_argmin = tf.constant([[61, 38, 26, 65, 44, 36],
                        [10, 15, 82, 42, 78, 43],
                        [71, 30, 22, 57, 42, 16]])
print(tf.math.argmax(x_argmax)) #returns the index of the maximum value in each column
print(tf.math.argmax(x_argmax, axis=1)) #returns the index of the maximum value in each row
print(tf.math.argmin(x_argmin)) #returns the index of the minimum value in each column
print(tf.math.argmin(x_argmin, axis=1)) #returns the index of the minimum value in each row

tf.Tensor([2 0 1 0 1 1], shape=(6,), dtype=int64)
tf.Tensor([3 2 0], shape=(3,), dtype=int64)
tf.Tensor([1 1 2 1 2 2], shape=(6,), dtype=int64)
tf.Tensor([2 0 5], shape=(3,), dtype=int64)


In [22]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])
y = tf.constant([[7, 8, 9], [10, 11, 12]])
tf.pow(x, y)  # [[1^7, 2^8, 3^9], [4^10, 5^11, 6^12]] = [[1, 256, 19683], [1048576, 48828125, 2176782336]]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[          1,         256,       19683],
       [    1048576,    48828125, -2118184960]])>

In [23]:
x_2d = tf.constant([[1, 2, 3],
                     [4, 5, 6],
                    [7, 8, 9], 
                    [10, 11, 12],
                    [13, 14, 15]])
print(tf.math.reduce_sum(
    x_2d,
    axis=0,
    keepdims=True,
    name=None))

print(tf.math.reduce_sum(
    x_2d,
    axis=1,
    keepdims=True,
    name=None))


tf.Tensor([[35 40 45]], shape=(1, 3), dtype=int32)
tf.Tensor(
[[ 6]
 [15]
 [24]
 [33]
 [42]], shape=(5, 1), dtype=int32)


In [24]:
tf.math.top_k(
    x_2d,
    k=2,
    sorted=True,
    name=None
)

TopKV2(values=<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 3,  2],
       [ 6,  5],
       [ 9,  8],
       [12, 11],
       [15, 14]])>, indices=<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1],
       [2, 1],
       [2, 1]])>)

linear algebra operations

In [25]:
x=tf.constant([[1,2,3],[4,5,6]])
y=tf.constant([[7,8],[9,10],[11,12]])
tf.linalg.matmul(
    x,
    y,
    transpose_a=False,
    transpose_b=False,
    adjoint_a=False,
    adjoint_b=False,
    a_is_sparse=False,
    b_is_sparse=False,
    name=None
)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [28]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]],dtype=tf.float32) 
# (lower<0 or m - n <= lower) and (upper<0 or n-m <= upper)
#m is for rows and n is for columns
tf.linalg.band_part( 
    tensor_two_d,
    num_lower=0,
    num_upper=1,
    name=None
)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 1.,  2.,  0.],
       [ 0.,  5., -1.],
       [ 0.,  0.,  6.],
       [ 0.,  0.,  0.]], dtype=float32)>

In [40]:
tensor = tf.constant([[1,2,3],[4,5,6],[3,2,1]],dtype=tf.float32)
tensor_transpose = tf.linalg.matrix_transpose(
    tensor,
    conjugate=False,
    name=None
)
print(tensor_transpose)

tf.Tensor(
[[1. 4. 3.]
 [2. 5. 2.]
 [3. 6. 1.]], shape=(3, 3), dtype=float32)


In [41]:
tensor@tensor_transpose #matrix multiplication

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[14., 32., 10.],
       [32., 77., 28.],
       [10., 28., 14.]], dtype=float32)>

In [44]:
s,u,v = tf.linalg.svd(tensor) #singular value decomposition
print("s :")
print(s)
print("u :")
print(u)
print("v :")
print(v)

s :
tf.Tensor([1.0029249e+01 2.1009851e+00 8.8105260e-08], shape=(3,), dtype=float32)
u :
tf.Tensor(
[[ 0.36064753 -0.455819   -0.8137334 ]
 [ 0.8744579  -0.1382287   0.4649905 ]
 [ 0.32443294  0.8792734  -0.34874287]], shape=(3, 3), dtype=float32)
v :
tf.Tensor(
[[ 0.4817686   0.7753915   0.40824848]
 [ 0.5725702   0.07413942 -0.8164965 ]
 [ 0.66337186 -0.6271134   0.40824822]], shape=(3, 3), dtype=float32)


In [47]:
import numpy as np
a = np.array([
    [2,6,5,2],
    [2,-2,2,3],
    [1,5,4,0]
])

b = np.array([
    [2,9,0,3,0],
    [3,6,8,-2,2],
    [1,3,5,0,1],
    [3,0,2,0,5]])

print("Matmul C = : \n"
      ,np.matmul(a,b))

print("Einsum C = : \n",
      np.einsum('ij,jk->ik',a,b))


Matmul C = : 
 [[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
Einsum C = : 
 [[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


In [51]:
A =np.array([[1,2],[3,4]])
B =np.array([[5,6],[7,8]])
print("Einsum C = : \n",np.einsum('ij,jk->ik',A,B))
print("Matmul C = : \n",np.matmul(A,B))
print("Einsum C = : \n",np.einsum('ij,ij->ij',A,B))


Einsum C = : 
 [[19 22]
 [43 50]]
Matmul C = : 
 [[19 22]
 [43 50]]
Einsum C = : 
 [[ 5 12]
 [21 32]]


In [52]:
A =np.array([[1,2],[3,4]]) 
print("Transpose A = : \n",np.transpose(A))
print("Einsum Transpose A = : \n",np.einsum('ij->ji',A))

Transpose A = : 
 [[1 3]
 [2 4]]
Einsum Transpose A = : 
 [[1 3]
 [2 4]]


In [57]:
#batch matrix multiplication
A = np.array([[[1,2,4],[6,3,4],[2,8,7]],
              [[9,4,9],[10,3,1],[11,9,1]],
              [[12,5,6],[13,7,8],[14,0,5]]])

B = np.array([[[15,5,6],[14,7,8],[13,0,5]],
              [[12,7,3],[11,6,2],[10,1,0]],
              [[9,1,2],[8,2,1],[7,3,4]]])
print("Batch Matmul C = : \n",np.matmul(A,B))
print("Einsum Batch Matmul C = : \n",np.einsum('bij,bjk->bik',A,B))

print("Sum of A = : \n",np.sum(A))
print("Einsum Sum of A = : \n",np.einsum('ijk->',A))

Batch Matmul C = : 
 [[[ 95  19  42]
  [184  51  80]
  [233  66 111]]

 [[242  96  35]
  [163  89  36]
  [241 132  51]]

 [[190  40  53]
  [229  51  65]
  [161  29  48]]]
Einsum Batch Matmul C = : 
 [[[ 95  19  42]
  [184  51  80]
  [233  66 111]]

 [[242  96  35]
  [163  89  36]
  [241 132  51]]

 [[190  40  53]
  [229  51  65]
  [161  29  48]]]
Sum of A = : 
 164
Einsum Sum of A = : 
 164


In [58]:
# attention(Q,K,V) = softmax(QK^T/sqrt(d_k))V
#attenstion is used for self attention mechanism in transformer
Q = np.array([[1,2,4],[6,3,4],[2,8,7]])
K = np.array([[5,6,7],[8,9,10],[11,12,13]])
V = np.array([[14,15,16],[17,18,19],[20,21,22]])
d_k = 3
QK = np.matmul(Q,K.T)
QK = QK/np.sqrt(d_k)
attention = np.matmul(QK,V)
print("Attention = : \n",attention)

Attention = : 
 [[2016.10714001 2130.42249331 2244.73784661]
 [3521.25929179 3720.44513466 3919.63097753]
 [4828.9576515  5102.6216791  5376.28570669]]


In [61]:
Q = np.random.rand(32,64,512)
#Q = batchsize, s_q,modelsize
#K = batchsize, s_k,modelsize
#s_q and s_k are the sequence length
K = np.random.rand(32,128,512)
np.einsum('bqm,bkm->bqk',Q,K).shape

(32, 64, 128)

In [66]:
#batch and chunks for matrix size 4*8,chunks size 4*2
A = np.random.rand(2,4,4,2) #(chunk,batch,
B = np.random.rand(2,4,4,1)
np.einsum('bcij,bcik->bckj',A,B).shape

(2, 4, 1, 2)

In [85]:
tensor = tf.constant([[[1,2,3],[4,5,6],[3,2,1]],
                      [[4,5,6],[7,8,9],[6,5,4]],
                      [[3,2,1],[6,5,4],[9,8,7]]],
                     dtype=tf.float32)
print(tensor.shape)
print(tf.expand_dims(tensor,axis=0).shape)

x = tf.constant([[3,4,5],[9,5,2],[7,3,1]],dtype=tf.float32)
print(tf.expand_dims(x,axis=1).shape)
print(tf.expand_dims(x,axis=0).shape)
print(tf.expand_dims(x,axis=2).shape)
x_squeezed = tf.squeeze(x)
print("squeezed:",x_squeezed.shape)
print("reshape:",tf.reshape(x,[1,9]).shape)

(3, 3, 3)
(1, 3, 3, 3)
(3, 1, 3)
(1, 3, 3)
(3, 3, 1)
squeezed: (3, 3)
reshape: (1, 9)


In [88]:
t1 = tf.constant([[1,2,3],[4,5,6],[3,2,1]],dtype=tf.float32)
t2 = tf.constant([[4,5,6],[7,8,9],[6,5,4]],dtype=tf.float32)
print(tf.concat([t1,t2],axis=0).shape)
print(tf.concat([t1,t2],axis=0))
print(tf.concat([t1,t2],axis=1).shape)
print(tf.concat([t1,t2],axis=1))


(6, 3)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [3. 2. 1.]
 [4. 5. 6.]
 [7. 8. 9.]
 [6. 5. 4.]], shape=(6, 3), dtype=float32)
(3, 6)
tf.Tensor(
[[1. 2. 3. 4. 5. 6.]
 [4. 5. 6. 7. 8. 9.]
 [3. 2. 1. 6. 5. 4.]], shape=(3, 6), dtype=float32)


In [97]:
print(tf.stack([t1,t2],axis=0).shape)
print(tf.stack([t1,t2],axis=1).shape)

(2, 3, 3)
(3, 2, 3)


In [99]:
tf.concat([tf.expand_dims(t1,axis=0),tf.expand_dims(t2,axis=0)],axis=0).shape

TensorShape([2, 3, 3])

In [102]:
print(tf.pad(
    t1,
    paddings=[[1, 2], [2, 1]],
    mode='CONSTANT',
    constant_values=0,
    name=None
))

print(tf.pad(
    t1,
    paddings=[[1, 2], [2, 1]],
    mode='REFLECT',
    constant_values=0,
    name=None
))

print(tf.pad(
    t1,
    paddings=[[1, 2], [2, 1]],
    mode='SYMMETRIC',
    constant_values=0,
    name=None
))

tf.Tensor(
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 3. 0.]
 [0. 0. 4. 5. 6. 0.]
 [0. 0. 3. 2. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]], shape=(6, 6), dtype=float32)
tf.Tensor(
[[6. 5. 4. 5. 6. 5.]
 [3. 2. 1. 2. 3. 2.]
 [6. 5. 4. 5. 6. 5.]
 [1. 2. 3. 2. 1. 2.]
 [6. 5. 4. 5. 6. 5.]
 [3. 2. 1. 2. 3. 2.]], shape=(6, 6), dtype=float32)
tf.Tensor(
[[2. 1. 1. 2. 3. 3.]
 [2. 1. 1. 2. 3. 3.]
 [5. 4. 4. 5. 6. 6.]
 [2. 3. 3. 2. 1. 1.]
 [2. 3. 3. 2. 1. 1.]
 [5. 4. 4. 5. 6. 6.]], shape=(6, 6), dtype=float32)


In [110]:
params = tf.constant([[1,2,3],[4,5,6],[3,2,1]],dtype=tf.float32)
print(tf.tile(params,[1,3]))

paramss = tf.constant(['p0','p1','p2','p3','p4','p5'])
print(paramss[1:4])
print(tf.gather(paramss,tf.range(1,4)))
print(tf.gather(paramss,[0,5,3]))

tf.Tensor(
[[1. 2. 3. 1. 2. 3. 1. 2. 3.]
 [4. 5. 6. 4. 5. 6. 4. 5. 6.]
 [3. 2. 1. 3. 2. 1. 3. 2. 1.]], shape=(3, 9), dtype=float32)
tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
tf.Tensor([b'p1' b'p2' b'p3'], shape=(3,), dtype=string)
tf.Tensor([b'p0' b'p5' b'p3'], shape=(3,), dtype=string)


In [113]:
params = tf.constant(
    [
        [0,1,2],
        [10,11,12],
        [20,21,22],
        [30,31,32]
    ],dtype = tf.float32
)
print(tf.gather(params,[0,3],axis=0))
print(tf.gather(params,[0,1],axis=1))

tf.Tensor(
[[ 0.  1.  2.]
 [30. 31. 32.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.  1.]
 [10. 11.]
 [20. 21.]
 [30. 31.]], shape=(4, 2), dtype=float32)


In [117]:
# tf.gather_nd
params = tf.constant(
    [
        [0,1,2],
        [10,11,12],
        [20,21,22],
        [30,31,32]
    ],dtype = tf.float32
)
indices = tf.constant([[1],[2]])
print(tf.gather_nd(params,indices))

params = tf.constant(
    [
        [
            ['a0','b0'],
            ['c0','d0']
        ],
        [
            ['a1','b1'],
            ['c1','d1']
        ]
    ]
)

indices = tf.constant([[0,1],[1,0]])

tf.gather_nd(params,indices)

tf.Tensor(
[[10. 11. 12.]
 [20. 21. 22.]], shape=(2, 3), dtype=float32)


<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

ragged tensors

In [126]:
tensor_2d = tf.constant([
    [1,2,3],
    [4,5,6],
    [3,2,1]],dtype=tf.float32)

print(tensor_2d.shape)

tensor_2ds = [
    [1,2,3],
    [4,],
    [2,1,3],
    [3,2]]
tensor_2ds = tf.ragged.constant(tensor_2ds)

print(tensor_2ds)

(3, 3)
<tf.RaggedTensor [[1, 2, 3], [4], [2, 1, 3], [3, 2]]>


In [127]:
print(tensor_2ds.from_row_lengths(
    values = [3,1,4,1,5,9,2,6],
    row_lengths=[4,0,3,1,0]
))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]>


In [135]:
print(tf.sparse.SparseTensor(
    indices=[[1, 1], [3, 4]],
    values=[11, 56],
    dense_shape=[5, 6]
))
print("--------------------------------------------------------------")
print(tf.sparse.to_dense(tf.sparse.SparseTensor(
    indices=[[1, 1], [3, 4]],
    values=[11, 56],
    dense_shape=[5, 6])
))


SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))
--------------------------------------------------------------
tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 56  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)


In [139]:
tensor_string = tf.constant(["Hello, World!","Hi"])
print(tensor_string)
print(tf.strings.join(tensor_string,separator=" "))
print(tf.strings.lower(tensor_string))
print(tf.strings.upper(tensor_string))

tf.Tensor([b'Hello, World!' b'Hi'], shape=(2,), dtype=string)
tf.Tensor(b'Hello, World! Hi', shape=(), dtype=string)
tf.Tensor([b'hello, world!' b'hi'], shape=(2,), dtype=string)
tf.Tensor([b'HELLO, WORLD!' b'HI'], shape=(2,), dtype=string)


In [149]:
x=tf.constant([[1,2,3],[4,5,6]])
x_var = tf.Variable(x,name ="var1",trainable=True)
print(x_var)
print(x_var.assign([[4,5,6],[7,8,9]]))
print(x_var.assign_add([[1,1,1],[1,1,1]]))
print(x_var.assign_sub([[3,7,1],[8,2,9]]))

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 5,  6,  7],
       [ 8,  9, 10]])>
<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int32, numpy=
array([[ 2, -1,  6],
       [ 0,  7,  1]])>


In [161]:
with tf.device('GPU:0'):
    x_var = tf.Variable([[1,2,3],[4,5,6]],name ="var1",trainable=True)
    print(x_var)

with tf.device('CPU:0'):
    x_tensor = tf.constant([[1,2,3],[4,5,6]])
    print(x_tensor)

print(x_var.device)
print(x_tensor.device)

<tf.Variable 'var1:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
